### ISSUE TITLE
Node server start error

### ISSUE THREAD

**Issue by arey** [spring-petclinic/spring-petclinic-reactjs#2]
I've got this error when I start the Node JS server. My Node and NPM are up to date:
* node v7.2.1
* npm  v3.10.9

Any idea ?
```
 ./run.sh

> spring-petclinic-reactjs@0.0.1 start /Dev/spring-petclinic-reactjs/client
> node server.js

Starting the development server...

ts-loader: Using typescript@2.1.4 and /Users/arey/Dev/GitHub/spring-petclinic-reactjs/client/tsconfig.json
/Users/arey/Dev/GitHub/spring-petclinic-reactjs/client/node_modules/typescript/lib/typescript.js:3177
                throw new Error("Debug Failure. False expression: " + (message || "") + verboseDebugString);
                ^

Error: Debug Failure. False expression: 
    at Object.assert (/Users/arey/Dev/GitHub/spring-petclinic-reactjs/client/node_modules/typescript/lib/typescript.js:3177:23)
    at resolveExternalModule (/Users/arey/Dev/GitHub/spring-petclinic-reactjs/client/node_modules/typescript/lib/typescript.js:25418:30)
    at resolveExternalModuleNameWorker (/Users/arey/Dev/GitHub/spring-petclinic-reactjs/client/node_modules/typescript/lib/typescript.js:25380:20)
    at mergeModuleAugmentation (/Users/arey/Dev/GitHub/spring-petclinic-reactjs/client/node_modules/typescript/lib/typescript.js:24590:34)
    at initializeTypeChecker (/Users/arey/Dev/GitHub/spring-petclinic-reactjs/client/node_modules/typescript/lib/typescript.js:42705:25)
    at Object.createTypeChecker (/Users/arey/Dev/GitHub/spring-petclinic-reactjs/client/node_modules/typescript/lib/typescript.js:24428:9)
    at getDiagnosticsProducingTypeChecker (/Users/arey/Dev/GitHub/spring-petclinic-reactjs/client/node_modules/typescript/lib/typescript.js:62530:93)
    at Object.getGlobalDiagnostics (/Users/arey/Dev/GitHub/spring-petclinic-reactjs/client/node_modules/typescript/lib/typescript.js:62848:41)
    at Object.getCompilerOptionsDiagnostics (/Users/arey/Dev/GitHub/spring-petclinic-reactjs/client/node_modules/typescript/lib/typescript.js:79004:84)
    at Compiler.<anonymous> (/Users/arey/Dev/GitHub/spring-petclinic-reactjs/client/node_modules/ts-loader/index.js:308:72)

npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/Cellar/node/7.2.1/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! spring-petclinic-reactjs@0.0.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the spring-petclinic-reactjs@0.0.1 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the spring-petclinic-reactjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs spring-petclinic-reactjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls spring-petclinic-reactjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Dev/spring-petclinic-reactjs/client/npm-debug.log
```

**Comment by arey** [comment]
Thanks @nilshartmann Petclinic now works on my desktop
